#!/bin/bash

set -e

# display news items and mark them as read.
eselect news read new | grep -v '^No news is good news.' || :

# dummy run emerge first, so global updates don't clutter the output.
emerge --info &>/dev/null
eout=$(emerge @world -NDuqvp --color=y)

if [[ "${eout}" != "" ]]; then
	echo "${eout}"
	echo
	read -p "press ENTER to merge packages or CTRL-C to abort ... "
	echo
	emerge @world -NDu
fi

# first try to resolve preserved-libs with binpkgs. if this fails, the second
# run will pick up remaining libs.
emerge @preserved-rebuild
emerge @preserved-rebuild --usepkg=n

# this fucker needs to be run after every upgrade, since noone can be sure what
# has been broken. dude, srsly - can't we simply have PYTHON_TARGETS?
eselect python update --python2
python-updater -dmanual -- --usepkg
python-updater -dmanual -- --usepkg=n

# same crap as with python ...
perl-cleaner --all -- --usepkg
perl-cleaner --all -- --usepkg=n

# these packages need to be remerged every time, because either revdep-rebuild
# will not pick them up, or their build system is so horribly broken that even
# API compatible libraries won't be accepted at run-time because of version
# mismatches.
# TODO: haunt the developers of this crap.
BUMS="
dev-ruby/nokogiri
dev-ruby/rmagick
"

for bum in $BUMS; do
	if [[ "$(qlist -IC ${bum})" != "" ]]; then
		emerge -1 --usepkg=n ${bum}
	fi
done

# run lafilefixer to get rid of fucking annoying libtool archive dependency
# crap. aw man. this is getting worse every day.
emerge -n dev-util/lafilefixer
lafilefixer --justfixit

# finally, after all this crap, run revdep-rebuild to pick up remaining
# packages that have broken lib dependencies.
EMERGE_DEFAULT_OPTS="" revdep-rebuild -i -- --quiet-build --with-bdeps=y --binpkg-respect-use=y --usepkg=n

# force latest gcc version
gcc-config $(gcc-config -l|tail -n1|awk '{print $2}')

# update config files
etc-update

# commit any changes to /etc
cd /etc
git add -A .
git ci -m 'automatic commit after updateworld'

# run chef-client to fixup configs overwritten by etc-update
chef-client -V

# cleanup unneeded dependencies
emerge --depclean -aq

exit 0
